CREATE TABLE "ROLES" (
	"ROLE_ID"	INTEGER NOT NULL,
	"ROLE_NAME"	TEXT NOT NULL UNIQUE,
	"MANAGE_USER_LIST"	INTEGER NOT NULL,
	"MANAGE_USER_TIMESHEET"	INTEGER NOT NULL,
	PRIMARY KEY("ROLE_ID" AUTOINCREMENT)
);
);