CREATE TABLE "USER_SETTINGS" (
	"USER_ID"	INTEGER NOT NULL,
	"USER_PREFERED_WORKING_HOURS"	INTEGER NOT NULL,
	"USER_ROLE_ID"	INTEGER,
	FOREIGN KEY("USER_ID") REFERENCES USERS(USER_ID),
	FOREIGN KEY("USER_ROLE_ID") REFERENCES ROLES(ROLE_ID),
	PRIMARY KEY("USER_ID") 
);